@startuml
left to right direction

abstract libros
abstract DVD
abstract revistas
abstract VHS
abstract Internet
abstract caset

libreria -- recursos
recursos <-- libros
recursos <-- DVD
recursos <-- revistas
recursos <-- VHS
recursos <-- Internet 
recursos <-- caset 

DVD : tamaño_en_MegaBites
VHS : calidad_cinta
Internet : velocidad_de_la_red
caset : capacidad_del_disco
revistas : formato_impresion
libros : cantidad_de_paginas
recursos : genero 
recursos : autor/productor
recursos : cantidad
recursos : Titulo 
recursos : año_de_publicacion
recursos : prestado_disponible
recursos : estado_de_uso
libreria : organizar_recurso()
libreria : sacar_devolver_libros()

@enduml